import { CatalogDefinition, FormatType } from "./types";
import { catalogToPrompt } from "./catalogToPrompt";

/**
 * Copy raw JSON to clipboard
 */
export function exportJson(text: string): string {
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

/**
 * Export as LLM system prompt with catalog embedded
 */
export function exportAsLLMPrompt(
  catalog: CatalogDefinition,
  format: FormatType
): string {
  return catalogToPrompt(catalog, format);
}

/**
 * Export as a TypeScript catalog file
 */
export function exportAsCatalogTs(catalog: CatalogDefinition): string {
  return `import type { CatalogDefinition } from "./types";

export const CATALOG: CatalogDefinition = ${JSON.stringify(catalog, null, 2)};
`;
}

/**
 * Convert A2UI spec to proper JSONL (one JSON object per line)
 */
export function exportAsJsonl(text: string): string {
  try {
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed)) {
      return parsed.map((msg) => JSON.stringify(msg)).join("\n");
    }
    return text;
  } catch {
    return text;
  }
}

/**
 * Encode spec as base64 URL parameter for sharing
 */
export function exportAsShareUrl(text: string, format: FormatType): string {
  const payload = JSON.stringify({ format, spec: text });
  const encoded = btoa(unescape(encodeURIComponent(payload)));
  const baseUrl = typeof window !== "undefined" ? window.location.origin : "";
  return `${baseUrl}/playground?share=${encoded}`;
}

/**
 * Decode a shared URL parameter back to spec + format
 */
export function decodeShareUrl(
  shareParam: string
): { format: FormatType; spec: string } | null {
  try {
    const decoded = decodeURIComponent(escape(atob(shareParam)));
    const parsed = JSON.parse(decoded);
    return { format: parsed.format, spec: parsed.spec };
  } catch {
    return null;
  }
}

/**
 * Generate a self-contained React component that renders the spec
 */
export function exportAsReactComponent(
  text: string,
  format: FormatType
): string {
  return `"use client";

import React from "react";

// Generated by GenUI Playground
// Format: ${format}

const spec = ${text};

// Component renderers
const renderers: Record<string, React.FC<any>> = {
  Card: ({ title, subtitle, description, children }) => (
    <div style={{ border: "1px solid #e5e7eb", borderRadius: 12, padding: 24, background: "#fff" }}>
      {title && <h3 style={{ fontSize: 18, fontWeight: 600, margin: 0 }}>{title}</h3>}
      {subtitle && <p style={{ fontSize: 14, color: "#6b7280", marginTop: 4 }}>{subtitle}</p>}
      {description && <p style={{ fontSize: 14, color: "#374151", marginTop: 8 }}>{description}</p>}
      <div style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 12 }}>{children}</div>
    </div>
  ),
  Metric: ({ label, value, trend }) => (
    <div style={{ padding: 16, background: "#f9fafb", borderRadius: 8 }}>
      {label && <p style={{ fontSize: 13, color: "#6b7280" }}>{label}</p>}
      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
        <span style={{ fontSize: 24, fontWeight: 700 }}>{value}</span>
        {trend === "up" && <span style={{ color: "#22c55e" }}>↑</span>}
        {trend === "down" && <span style={{ color: "#ef4444" }}>↓</span>}
      </div>
    </div>
  ),
  Text: ({ content, size }) => {
    const sizes: Record<string, number> = { sm: 14, md: 16, lg: 20, xl: 24 };
    return <p style={{ fontSize: sizes[size || "md"] || 16 }}>{content}</p>;
  },
  Button: ({ label, variant }) => {
    const styles: Record<string, React.CSSProperties> = {
      primary: { background: "#2563eb", color: "#fff" },
      secondary: { background: "#f3f4f6", color: "#111" },
      danger: { background: "#ef4444", color: "#fff" },
      ghost: { background: "transparent", color: "#2563eb" },
    };
    return <button style={{ padding: "8px 16px", borderRadius: 6, border: "none", cursor: "pointer", fontWeight: 500, ...(styles[variant || "primary"]) }}>{label}</button>;
  },
  Badge: ({ label, color }) => {
    const colors: Record<string, string> = { success: "#22c55e", warning: "#f59e0b", danger: "#ef4444", info: "#3b82f6", neutral: "#6b7280" };
    return <span style={{ display: "inline-block", padding: "2px 10px", borderRadius: 999, fontSize: 12, fontWeight: 500, background: colors[color || "neutral"] + "20", color: colors[color || "neutral"] }}>{label}</span>;
  },
  Divider: () => <hr style={{ border: "none", borderTop: "1px solid #e5e7eb", margin: "8px 0" }} />,
  Stack: ({ direction, gap, children }) => {
    const gaps: Record<string, number> = { sm: 8, md: 16, lg: 24 };
    return <div style={{ display: "flex", flexDirection: direction || "column", gap: gaps[gap || "md"] || 16, flexWrap: "wrap" }}>{children}</div>;
  },
  Table: ({ columns, rows }) => (
    <table style={{ width: "100%", borderCollapse: "collapse", border: "1px solid #e5e7eb" }}>
      <thead><tr>{columns?.map((c: string, i: number) => <th key={i} style={{ padding: "8px 12px", textAlign: "left", background: "#f9fafb", borderBottom: "1px solid #e5e7eb", fontSize: 12, fontWeight: 600 }}>{c}</th>)}</tr></thead>
      <tbody>{rows?.map((row: string[], ri: number) => <tr key={ri}>{row.map((cell, ci) => <td key={ci} style={{ padding: "8px 12px", borderBottom: "1px solid #f3f4f6", fontSize: 14 }}>{cell}</td>)}</tr>)}</tbody>
    </table>
  ),
  Input: ({ label, placeholder, type }) => (
    <div><label style={{ fontSize: 13, fontWeight: 500, display: "block", marginBottom: 4 }}>{label}</label><input type={type || "text"} placeholder={placeholder} style={{ padding: "8px 12px", border: "1px solid #d1d5db", borderRadius: 6, width: "100%" }} /></div>
  ),
  Select: ({ label, options }) => (
    <div><label style={{ fontSize: 13, fontWeight: 500, display: "block", marginBottom: 4 }}>{label}</label><select style={{ padding: "8px 12px", border: "1px solid #d1d5db", borderRadius: 6, width: "100%" }}>{options?.map((o: string, i: number) => <option key={i}>{o}</option>)}</select></div>
  ),
  Progress: ({ value, label, color }) => {
    const colors: Record<string, string> = { blue: "#3b82f6", green: "#22c55e", yellow: "#f59e0b", red: "#ef4444" };
    return <div>{label && <p style={{ fontSize: 13, marginBottom: 4 }}>{label}</p>}<div style={{ background: "#f3f4f6", borderRadius: 999, height: 8 }}><div style={{ width: \`\${value}%\`, background: colors[color || "blue"], height: "100%", borderRadius: 999, transition: "width 0.3s" }} /></div></div>;
  },
  Alert: ({ message, severity }) => {
    const styles: Record<string, { bg: string; border: string; text: string }> = {
      info: { bg: "#eff6ff", border: "#93c5fd", text: "#1d4ed8" },
      warning: { bg: "#fffbeb", border: "#fcd34d", text: "#b45309" },
      error: { bg: "#fef2f2", border: "#fca5a5", text: "#dc2626" },
      success: { bg: "#f0fdf4", border: "#86efac", text: "#16a34a" },
    };
    const s = styles[severity || "info"];
    return <div style={{ padding: "12px 16px", background: s.bg, border: \`1px solid \${s.border}\`, borderRadius: 8, color: s.text, fontSize: 14 }}>{message}</div>;
  },
};

${format === "json-render" ? `
function RenderElement({ id, elements }: { id: string; elements: Record<string, any> }) {
  const el = elements[id];
  if (!el) return null;
  const Comp = renderers[el.type];
  if (!Comp) return <div>Unknown: {el.type}</div>;
  return (
    <Comp {...el.props}>
      {el.children?.map((childId: string) => (
        <RenderElement key={childId} id={childId} elements={elements} />
      ))}
    </Comp>
  );
}

export default function GeneratedUI() {
  return <RenderElement id={spec.root} elements={spec.elements} />;
}
` : `
export default function GeneratedUI() {
  const components = spec.flatMap((msg: any) =>
    msg.updateComponents?.components || []
  );
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      {components.map((c: any) => {
        const type = Object.keys(c.component)[0];
        const Comp = renderers[type];
        if (!Comp) return <div key={c.id}>Unknown: {type}</div>;
        const props: Record<string, any> = {};
        for (const [k, v] of Object.entries(c.component[type] as Record<string, any>)) {
          props[k] = v.literalString ?? v.literalNumber ?? v.literalBoolean ?? v.path ?? v;
        }
        return <Comp key={c.id} {...props} />;
      })}
    </div>
  );
}
`}`;
}
