"use server";

import { v4 as uuidv4 } from "uuid";

// ─── Server Actions for Workspace Operations ─────────────────────────────────

export interface SaveResult {
  success: boolean;
  workspaceId: string;
  savedAt: number;
  error?: string;
}

export interface ForkResult {
  success: boolean;
  newWorkspaceId: string;
  forkedFrom: string;
  error?: string;
}

export interface ExportResult {
  success: boolean;
  format: string;
  data: string;
  filename: string;
  error?: string;
}

/**
 * Save workspace state to persistent storage.
 */
export async function saveWorkspace(
  workspaceId: string,
  rawText: string,
  format: string,
  name?: string
): Promise<SaveResult> {
  try {
    // TODO: When Supabase is configured, save to remote
    // For now, the client handles persistence via IndexedDB
    return {
      success: true,
      workspaceId,
      savedAt: Date.now(),
    };
  } catch (error) {
    return {
      success: false,
      workspaceId,
      savedAt: 0,
      error: error instanceof Error ? error.message : "Save failed",
    };
  }
}

/**
 * Fork a workspace — creates a copy with a new ID.
 */
export async function forkWorkspace(
  sourceWorkspaceId: string,
  rawText: string,
  format: string
): Promise<ForkResult> {
  try {
    const newId = uuidv4();

    // TODO: When Supabase is configured, create remote copy
    return {
      success: true,
      newWorkspaceId: newId,
      forkedFrom: sourceWorkspaceId,
    };
  } catch (error) {
    return {
      success: false,
      newWorkspaceId: "",
      forkedFrom: sourceWorkspaceId,
      error: error instanceof Error ? error.message : "Fork failed",
    };
  }
}

/**
 * Export workspace in specified format.
 */
export async function exportWorkspace(
  rawText: string,
  format: string,
  exportFormat: string
): Promise<ExportResult> {
  try {
    let data = rawText;
    let filename = `workspace-${Date.now()}.json`;

    switch (exportFormat) {
      case "json":
        data = rawText;
        filename = `spec.json`;
        break;

      case "html-standalone": {
        data = generateStandaloneHTML(rawText);
        filename = `preview.html`;
        break;
      }

      case "css-variables": {
        data = generateCSSVariables();
        filename = `tokens.css`;
        break;
      }

      case "react-component": {
        data = generateReactComponent(rawText, format);
        filename = `GeneratedUI.tsx`;
        break;
      }

      default:
        data = rawText;
        filename = `export.${exportFormat}`;
    }

    return {
      success: true,
      format: exportFormat,
      data,
      filename,
    };
  } catch (error) {
    return {
      success: false,
      format: exportFormat,
      data: "",
      filename: "",
      error: error instanceof Error ? error.message : "Export failed",
    };
  }
}

// ─── Export Helpers ───────────────────────────────────────────────────────────

function generateStandaloneHTML(specJson: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>GenUI Export</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-gray-50 p-8">
  <div id="spec-data" style="display:none">${specJson.replace(/</g, "&lt;")}</div>
  <div id="root" class="max-w-4xl mx-auto">
    <pre class="bg-white p-6 rounded-xl border shadow-sm overflow-auto text-sm">${specJson.replace(/</g, "&lt;")}</pre>
  </div>
</body>
</html>`;
}

function generateCSSVariables(): string {
  return `/* GenUI Design Tokens */
:root {
  --color-primary-500: #3b82f6;
  --color-primary-600: #2563eb;
  --color-success-500: #22c55e;
  --color-warning-500: #f59e0b;
  --color-danger-500: #ef4444;
  --color-neutral-100: #f3f4f6;
  --color-neutral-900: #111827;

  --spacing-xs: 4px;
  --spacing-sm: 8px;
  --spacing-md: 16px;
  --spacing-lg: 24px;
  --spacing-xl: 32px;

  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-full: 9999px;
}`;
}

function generateReactComponent(specJson: string, format: string): string {
  return `// Auto-generated by GenUI Studio
// Format: ${format}
// Generated: ${new Date().toISOString()}

import React from "react";

const spec = ${specJson};

export default function GeneratedUI() {
  return (
    <pre className="p-4 bg-gray-100 rounded-lg overflow-auto text-sm">
      {JSON.stringify(spec, null, 2)}
    </pre>
  );
}
`;
}
